strategy:
  matrix:
    linux:
      imageName: 'ruttm03'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)
  demands: maven

steps:
- task: Maven@3
  displayName: 'Maven sonar-sql-plugin install'
  inputs:
    mavenPomFile: 'src/sonar-sql-plugin/pom.xml'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/sonar-sql-plugin*.jar'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.artifactstagingdirectory)' 
    artifactName: 'build-$(Agent.OS)'
